Traceback (most recent call last):
  File "/Users/guy/miniconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/guy/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/guy/miniconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/guy/miniconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/guy/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/guy/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/Users/guy/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/guy/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
(
     usd_to_ils_rates
     .assign(Week = df.index.week)
     .groupby(['Week'])
     ['Day', 'Rate']
     .max()
     .style
     .background_gradient(cmap='summer', subset=['Rate'])
)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-20-9803dcc28f7b>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m (
[1;32m      2[0m      [0musd_to_ils_rates[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m      [0;34m.[0m[0massign[0m[0;34m([0m[0mWeek[0m [0;34m=[0m [0mdf[0m[0;34m.[0m[0mindex[0m[0;34m.[0m[0mweek[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m      [0;34m.[0m[0mgroupby[0m[0;34m([0m[0;34m[[0m[0;34m'Week'[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m      [0;34m[[0m[0;34m'Day'[0m[0;34m,[0m [0;34m'Rate'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: 'RangeIndex' object has no attribute 'week'
AttributeError: 'RangeIndex' object has no attribute 'week'

